spring:
  application:
    name: thewcore
  datasource:
    url: jdbc:postgresql://localhost:5432/thew
    username: thew
    password: thew
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
